refactor(lido adapter): refactored lido adapter as per the last updates
Opty-Fi/defi-adapters pull request #19
Opened 2022-01-25 14:07 UTC by mariogutval

Refactored Lido adapter created by niklr

#### PR Checklist

- [ ] Tests

2022-01-27 17:19 UTC, dhruvinparikh commented on test/1_ethereum/lido.fi/lido.fi-pools.json
> +    "rewardTokens": [],
@deepcrazy Please take a note of this change.

2022-01-27 17:19 UTC, dhruvinparikh approved these changes, later dismissed

2022-01-27 18:01 UTC, deepcrazy requested changes
1 minor doubt in lido eth gateway contract and 1 small change request.

2022-01-27 18:01 UTC, deepcrazy commented on contracts/1_ethereum/2_lido.fi/LidoEthGateway.sol
> +            IERC20(_liquidityPool).balanceOf(address(this)),
Doubt: I think it should be `_amount` instead of whole balance as `_amount` will be coming from LidoAdapter.sol which can be full balance or some amount, right?

2022-01-27 18:01 UTC, deepcrazy commented on test/1_ethereum/lido.fi/LidoAdapter.behavior.ts
> +    expect(actualRewardToken).to.be.eq("0x0000000000000000000000000000000000000000");
```suggestion
    expect(actualRewardToken).to.be.eq(hre.ethers.constants.AddressZero);
```

2022-01-27 18:01 UTC, deepcrazy commented on test/1_ethereum/lido.fi/lido.fi-pools.json
> +    "rewardTokens": [],
Yes, It is already like this in shared-defi-data as well as DB. This issue is coming from there itself.

2022-01-31 12:02 UTC, dhruvinparikh requested changes
- [ ]  Please include [AdapterInvestLimitBase](https://github.com/Opty-Fi/defi-adapters/blob/main/contracts/utils/AdapterInvestLimitBase.sol) and [AdapterModifiersBase.sol](https://github.com/Opty-Fi/defi-adapters/blob/main/contracts/utils/AdapterModifiersBase.sol) in `LidoAdapter.sol`

2022-02-07 19:15 UTC, deepcrazy approved these changes, later dismissed
Approving. Make sure to re-run CI/CD as well.

2022-02-07 20:47 UTC, dhruvinparikh requested changes

2022-02-07 20:47 UTC, dhruvinparikh commented on contracts/1_ethereum/2_lido.fi/LidoAdapter.sol
>  /////////////////////////////////////////////////////
- [ ] Remove this comment

2022-02-07 20:47 UTC, dhruvinparikh commented on contracts/1_ethereum/2_lido.fi/LidoAdapter.sol
> +contract LidoAdapter is IAdapter, IAdapterInvestLimit, AdapterModifiersBase {
!!Important!! 

- [ ]  update `getDepositSomeCodes` to use _getDepositAmount

2022-02-07 20:47 UTC, dhruvinparikh commented on test/1_ethereum/lido.fi/LidoAdapter.ts
> +        ["0x99fa011e33a8c6196869dec7bc407e896ba67fe3"],
- [ ] Declare a constant at the top of the file `const registryContractAddress="0x99fa011e33a8c6196869dec7bc407e896ba67fe3"`

2022-02-09 18:48 UTC, mariogutval commented
CI/CD: https://github.com/Opty-Fi/defi-adapters/actions/runs/1815321043

2022-02-09 19:08 UTC, dhruvinparikh approved these changes

2022-02-10 16:37 UTC, deepcrazy approved these changes

2022-02-10 16:38 UTC, merged