OPTY-393: Beefy invest limit
Opty-Fi/defi-adapters pull request #23
Opened 2022-03-29 18:14 UTC by mariogutval

- Added investLimit to Beefy
- Removed isContract calls
- Bumped up solidity version in Beefy adapter

#### PR Checklist

- [ ] Tests

2022-03-29 20:21 UTC, dhruvinparikh requested changes

2022-03-29 20:21 UTC, dhruvinparikh commented on contracts/2_matic/beefy.finance/BeefyFinanceAdapter.sol
> +    IAdapterStaking, //REPLACE IAdapterHarvest..
- [ ] remove this comment

2022-03-29 20:21 UTC, dhruvinparikh commented on contracts/1_ethereum/lido.fi/LidoAdapter.sol
>          maxDepositPoolPct[_underlyingToken] = _maxDepositPoolPct;
- [ ] please revert any changes made to lido as it is already deployed. We can curate in adapter refactoring document as what changes needs to be made.

2022-03-30 03:22 UTC, deepcrazy requested changes

2022-03-30 03:22 UTC, deepcrazy commented on contracts/2_matic/beefy.finance/BeefyFinanceAdapter.sol
>              ); //maybe there are two pools in case in some cases we wanted to deposit two tokens?
I think we can remove this comment.

2022-03-30 03:22 UTC, deepcrazy commented on contracts/2_matic/beefy.finance/BeefyFinanceAdapter.sol
>          }
Isn't following better? I think, we should check first if `_amount > 0` or not. and later check `_depositAmount > 0` or not. If =0, then revert the transaction.
```
  if (_amount > 0) {
      uint256 _depositAmount = _getDepositAmount(
              _liquidityPool,
              _underlyingToken,
              _amount,
              getPoolValue(_liquidityPool, address(0))
          );
        
        if (_depositAmount > 0) {
            _codes = new bytes[](3);
            _codes[0] = abi.encode(
                _underlyingToken,
                abi.encodeWithSignature("approve(address,uint256)", _liquidityPool, uint256(0))
            ); 
            _codes[1] = abi.encode(
                _underlyingToken,
                abi.encodeWithSignature("approve(address,uint256)", _liquidityPool, _depositAmount)
            );
            _codes[2] = abi.encode(_liquidityPool, abi.encodeWithSignature("deposit(uint256)", _depositAmount));
        }
  }
```

Thoughts?

2022-03-30 17:11 UTC, dhruvinparikh approved these changes

2022-03-30 17:13 UTC, deepcrazy approved these changes

2022-03-30 17:15 UTC, merged